### PR TITLE
- added markup conversion: markup generated by BBCodePlus is partiall…

### PR DESCRIPTION
**Pull request by elfuegobiz**
…y converted to Slack markup

### CODE REVIEW

**Comment by elfuegobiz** [comment]
Mb I missed some places where you also should add this conversion, but for issue comments (notes) it works.

**Comment by elfuegobiz** [comment]
And "partially" means it converts only those things which are supported by Slack markup, which is pretty poor. As for others, it just clears the markup.

**Comment by elfuegobiz** [comment]
Today I also improved look in different ways and added a russian translation.

**Comment by elfuegobiz** [comment]
And now it's even more nice =)

**Comment by infojunkie** [comment]
Great stuff, thanks! I reverted the project name styling in the notifications, so feel free to override strings on your end.

**Comment by elfuegobiz** [comment]
Why haven't you liked the project name styling?

**Comment by infojunkie** [comment]
Because I liked it better the way it was :-)

**Comment by elfuegobiz** [comment]
Ok, I see =)

**Pull request merged**
