### PR TITLE
Fail louder

### PR DESCRIPTION
**Pull request by bitwombat**
A patch to improve the error reporting if configuration options result in a bad curl_exec.

Trying something new - a default icon is sourced from the github repo (since it has to be a URL for slack to get to it).  Could use some help there because the icon gets squashed by Slack even though it's square.

*Need someone to please translate my new error message to German for lang/strings_german.txt

### CODE REVIEW

**Comment by infojunkie** [comment]
Great patch, thanks! I added a comment to the error reporting part, to try and display the actual error message that comes back from Slack (or cURL).

**Comment by infojunkie** [comment]
Regarding the bot icon, the way we're doing it is by uploading the Mantis icon on the Slack side, in the "Incoming WebHook" configuration.

**Comment by bitwombat** [comment]
You're welcome!  Happy to contribute.

Would you like me to remove the default icon from my patch?  I thought it was a bit weird hosting it on github, but new techniques often look that way at first.  I liked it because it's automatic...

If so, could we still include the mantis png in the repo, for convenience?  I had to hunt around for one, then mess with sizes...

Where did you add the comment to the error reporting part?  I don't see it in my branch or your base.

**Comment by infojunkie** [comment]
Dunno where the first one went, added it again: https://github.com/bitwombat/MantisBT-Slack/commit/b8b79bd9028407b5733d40bed29825c0d5c003af#commitcomment-14371198

It's fine by me to host the Mantis png here.

**Comment by bitwombat** [comment]
The way Mantis handles plugin errors and i18n seems very hard-coded to pull a string from the $MANTIS_ERROR array.  Can't find a way to pass in more details.  Still working on it - it sometimes displays "other output" after the error.

Please help me out with something - why are unquoted strings OK in PHP?  I'm missing a concept here.  Like ERROR_KARIM is just fine, even though its not a defined constant.  PHP just treats it as "ERROR_KARIM".

**Comment by bitwombat** [comment]
Alright, the error that comes back from curl is now printed below the error box (that's the way Mantis works - i18n text in the box, further errors below).  That took some hunting!  Ended up as one line of code.

**Comment by infojunkie** [comment]
Merged. Thanks for your contribution!

**Pull request merged**
